export const FOREX_PAIRS = [
  // Metals
  "XAUUSD", "XAGUSD", "XAUEUR", "XAUGBP",
  // Major Pairs
  "EURUSD", "GBPUSD", "USDJPY", "USDCHF", "AUDUSD", "USDCAD", "NZDUSD",
  // Crypto
  "BTCUSD", "ETHUSD", "LTCUSD", "XRPUSD", "SOLUSD", "DOGEUSD", "ADAUSD", "DOTUSD", "AVAXUSD", "BNBUSD",
  // Commodities
  "USOIL", "UKOIL", "NATGAS", "COPPER",
  // Minor Pairs
  "EURGBP", "EURJPY", "EURCHF", "EURAUD", "EURCAD", "EURNZD",
  "GBPJPY", "GBPCHF", "GBPAUD", "GBPCAD", "GBPNZD",
  "AUDJPY", "AUDCHF", "AUDCAD", "AUDNZD",
  "NZDJPY", "NZDCHF", "NZDCAD",
  "CADJPY", "CADCHF", "CHFJPY",
  // Exotic Pairs
  "USDTRY", "USDZAR", "USDMXN", "USDSGD", "USDHKD", "USDNOK", "USDSEK", "USDDKK", "USDPLN", "USDHUF", "USDCZK", "USDINR", "USDTHB",
  "EURTRY", "EURZAR", "EURNOK", "EURSEK", "EURDKK", "EURPLN", "EURHUF",
  "GBPTRY", "GBPZAR", "GBPNOK", "GBPSEK",
  // Indices (CFD)
  "US30", "US100", "US500", "UK100", "GER40", "FRA40", "JPN225", "AUS200",
  
  // Energies
  "XTIUSD", "XBRUSD",
];
